services:
  rabbitmq:
    build:
      context: .
      dockerfile: ./rabbitmq/dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"

  server1:
    build:
      context: ./server1
      dockerfile: dockerfile
    ports:
      - "8081:8081"
    depends_on: 
      rabbitmq:
        condition: service_healthy
  
  server2:
    build:
      context: ./server2
      dockerfile: dockerfile
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
