FROM golang:1.21.5 as builder
WORKDIR /app
COPY . .
RUN go mod download
ENV GOOS=linux
ENV CGO_ENABLED=0
RUN go build -o main ./cmd/server


FROM gcr.io/distroless/base
USER 1000:1000
COPY --from=builder /app/main /app/main
COPY --from=builder /app/config /app/config
ENV MODE=production
ENV RABBITMQ_HOST=rabbitmq
EXPOSE 8080
WORKDIR /app
CMD [ "./main" ]
