# config.yml
server:
  name: "server1"
  mode: "production"
  production:
    port: ":8081"
    read-timeout : 10
    write-timeout: 10
    hanler-timeout: 5
  debug:
    port: ":8081"
    read-timeout: 300
    write-timeout: 300
    hanler-timeout: 300

database:
