# config.yaml
server:
  name: "server1"
  mode: "production"
  production:
    port: ":8080"
    read-timeout : 10
    write-timeout: 10
  debug:
    port: ":8080"
    read-timeout: 300
    write-timeout: 300

database:
