# config.yml
server:
  name: "consumer-server"
  mode: "production"
  production:
    port: ":8082"
    read-timeout : 10
    write-timeout: 10
    hanler-timeout: 5
  debug:
    port: ":8082"
    read-timeout: 300
    write-timeout: 300
    hanler-timeout: 300

rabbitmq:
  host: "localhost"
  user: "guest"
  password: "guest"
  retry-count: 10
  retry-sleep: 5
  